camera:
  fov:
    width_mm: 304.8
    height_mm: 171.45
    width_px: 6240
    height_px: 4160
  focal_distance_mm: 300.0
  roi:
    width_px: 4160
    height_px: 4160
  dof_mm: 20.0
  frame:
    parent: panda_hand
    child: camera_link
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0 
    yaw: 0
part:
  model: /root/Inspection/Parts/2_5D_coupon.stl
  model_units: m
  point_cloud: /root/Inspection/Parts/canopy_oml.ply
  point_cloud_units: m
  point_cloud_color: 0.5 0.5 0.5
  frame:
    parent: world
    child: part_frame
    x: 0.5
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
inspection_root: /root/Inspection
defects:
  - name: "Default"
    camera:
        fov:
          width_mm: 304.8
          height_mm: 171.45
          width_px: 6240
          height_px: 4160
        focal_distance_mm: 300.0
        roi:
          width_px: 4160
          height_px: 4160
        dof_mm: 20.0
  - name: "9 micron scratch"
    camera: 
        fov:
          width_mm: 91.44
          height_mm: 51.435
        focal_distance_mm: 350.0
        roi:
          width_px: 4160
          height_px: 4160
        dof_mm: 20.0
  - name: "15 micron scratch"
    camera: 
        fov:
          width_mm: 152.4
          height_mm: 85.725
        focal_distance_mm: 150.0
        roi:
          width_px: 4160
          height_px: 4160
        dof_mm: 20.0
  - name: "30 micron scratch"
    camera: 
        fov:
          width_mm: 304.8
          height_mm: 171.45
        focal_distance_mm: 300.0
        roi:
          width_px: 4160
          height_px: 4160
        dof_mm: 20.0